module.exports = {
    SWITCH:   'SETTINGS_ACTION_TYPES_SWITCH',
    DROPDOWN: 'SETTINGS_ACTION_TYPES_DROPDOWN',
    COLOR:    'SETTINGS_ACTION_TYPES_COLOR',
    BUTTON:   'SETTINGS_ACTION_TYPES_BUTTON',
    TEXT:     'SETTINGS_ACTION_TYPES_TEXT',
    NUMBER:   'SETTINGS_ACTION_TYPES_NUMBER',
    LABEL:    'SETTINGS_ACTION_TYPES_LABEL',
    PASSWORD: 'SETTINGS_ACTION_TYPES_PASSWORD',
};
